services:
  kernel:
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
    volumes:
      - ./app/:/var/www/
      - ./build/php/apache2.conf:/etc/apache2/apache2.conf
      - ./build/php/apache_virtual.conf:/etc/apache2/sites-available/000-default.conf
      - ./build/php/php.ini:/usr/local/etc/php/php.ini
      - ./build/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./build/php/logs/access.log:/var/log/apache2/access.log
      - ./build/php/logs/error.log:/var/log/apache2/error.log
    ports:
      - "89:80"
      - "8444:443"
    depends_on:
      - db
    networks:
      commonnetwork:
        ipv4_address: 172.200.0.10
  db:
    env_file:
      - app/.env
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pet_db
    volumes:
      - ./build/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      commonnetwork:
        ipv4_address: 172.200.0.20
networks:
  commonnetwork:
    ipam:
      config:
        - subnet: 172.200.0.0/16